url=https://opensource-demo.orangehrmlive.com
browser=chromium
headless=false

username=Admin
password=admin123

implicitWait=5000
explicitWait=10000

screenshotOnFail=true

reportPath=reports/ExtentReport.html

env=QA